name: gestion_condominios
description: Aplicacion movil Flutter para gestion de condominios
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.0
  flutter_hooks: ^0.20.5
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  animated_list_plus: ^0.5.0
  rive: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
